team_1 = Team.create(name: "Team 1")
team_2 = Team.create(name: "Team 2")

pokemon_11 = Pokemon.create(name: "Abra", type: "Psychic", img: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/63.png", dex_num: 63, team_id: 1)
pokemon_12 = Pokemon.create(name: "Charizard", type: "Fire / Flying", img: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/6.png", dex_num: 6, team_id: 1)
pokemon_13 = Pokemon.create(name: "Arceus", type: "Normal", img: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/493.png", dex_num: 493, team_id: 1)
pokemon_14 = Pokemon.create(name: "Arcanine", type: "Fire", img: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/59.png", dex_num: 59, team_id: 1)
pokemon_15 = Pokemon.create(name: "Magnemite", type: "Electric / Steel", img: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/81.png", dex_num: 81, team_id: 1)
pokemon_16 = Pokemon.create(name: "Steelix", type: "Steel / Ground", img: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/208.png", dex_num: 208, team_id: 1)

pokemon_21 = Pokemon.create(name: "Zoroark", type: "Dark", img: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/571.png", dex_num: 571, team_id: 2)
pokemon_22 = Pokemon.create(name: "Ditto", type: "Normal", img: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/132.png", dex_num: 132, team_id: 2)
pokemon_23 = Pokemon.create(name: "Groudon", type: "Ground", img: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/383.png", dex_num: 383, team_id: 2)
pokemon_24 = Pokemon.create(name: "Azelf", type: "Psychic", img: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/482.png", dex_num: 482, team_id: 2)
pokemon_25 = Pokemon.create(name: "Zacian", type: "Fairy", img: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/888.png", dex_num: 888, team_id: 2)
pokemon_26 = Pokemon.create(name: "Budew", type: "Grass / Poison", img: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/406.png", dex_num: 406, team_id: 2)